In [2]:
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import polars as pl
import pandas as pd
import seaborn as sns
import sys
import os
from pathlib import Path

In [3]:
sys.path.insert(1, os.path.abspath(".."))

In [4]:
lf = pl.scan_parquet("../data/preprocessed_all_data.parquet")

In [5]:
# lf = df_all.lazy()
df_all = lf.collect()

In [65]:

# The "Anchor" for your Rolling Window
expr_culture_orders = (
    # Look for the ORDER or PROCEDURE
    (pl.col("event_full_name").str.to_lowercase().str.contains("order")) &
    (pl.col("event_full_name").str.to_lowercase().str.contains("culture")) &
    
    # Filter for the actual REQUEST (Procedure), not the Result
    (pl.col("event_full_name").str.to_lowercase().str.contains("procedure"))
)


expr_antibiotics_gold_standard = (
    (pl.col("Event_Grouper") == "Antibiotics") & 
    
    # 1. INCLUSION: Must be a systemic route
    (pl.col("event_full_name").str.to_lowercase().str.contains(r"\biv\b|intravenous|infusion|injection|push|piggy back"))&
    
    # 2. EXCLUSION: The "Not Sepsis" Filter
    ~(pl.col("event_full_name").str.to_lowercase().str.contains(
        r"dialysis|"        # Maintenance fluids
        r"heparin|"         # Line flushes
        r"lock solution|"   # Catheter cleaning
        r"chemo|"           # Cancer treatment
        r"rubicin|"         # Specific chemo agents (Doxorubicin, etc.)
        r"epoch|"           # Chemo cocktail
        r"intravitreal|"    # Eye injections (Local)
        r"intrapleural|"    # Lung cavity (Local/Mechanical)
        r"alteplase|"       # Clot busters
        r"activase"         # Clot busters
    ))
)

def detect_sepsis_suspicion(lf: pl.LazyFrame, expr_antibiotics_gold_standard: pl.Expr,
                            expr_culture_orders: pl.Expr):
    lf_abx = lf.filter(
        expr_antibiotics_gold_standard
    ).select(
        "PAT_ENC_CSN_ID",
        pl.col("Event_DateTime").alias("ABX_Time")
    ).sort("ABX_Time")

    lf_culture = lf.filter(
        expr_culture_orders 
    ).select(
        "PAT_ENC_CSN_ID",
        pl.col("Event_DateTime").alias("culture_Time")
    ).sort("culture_Time")

    lf_suspected_backward = lf_abx.join_asof(
        lf_culture,
        left_on="ABX_Time",
        right_on="culture_Time",
        by="PAT_ENC_CSN_ID",
        strategy="backward",
        tolerance="24h"
    ).filter(pl.col("culture_Time").is_not_null())

    lf_suspected_forward = lf_abx.join_asof(
        lf_culture,
        left_on="ABX_Time",
        right_on="culture_Time",
        by="PAT_ENC_CSN_ID",
        strategy="forward",
        tolerance="72h"
    ).filter(pl.col("culture_Time").is_not_null())

    # Combine matches and pick the EARLIEST of the two times
    df_suspected_infection = (
        pl.concat([lf_suspected_backward, lf_suspected_forward])
        .unique()
        .with_columns(
            # Sepsis Time Zero = Min(Abx Time, Culture Time)
            pl.min_horizontal(["ABX_Time", "culture_Time"]).alias("Suspected_Infection_Time")
        )
        # Get the FIRST episode per encounter
        .group_by("PAT_ENC_CSN_ID")
        .agg(pl.col("Suspected_Infection_Time").min())
        .collect()
    )
    return df_suspected_infection, lf_suspected_backward, lf_suspected_forward

df_suspected_infection, lf_suspected_backward, lf_suspected_forward = detect_sepsis_suspicion(
    # df_all.lazy(),
    lf,
    expr_antibiotics_gold_standard, expr_culture_orders
)
print(df_suspected_infection.shape)

(3595, 2)

sys:1: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided

In [6]:
lf_suspected = pl.concat([lf_suspected_backward, lf_suspected_forward]).collect()

In [9]:
df_all.filter(
    (pl.col("Event_Grouper") == 'Antibiotics')&
    (pl.col("event_full_name")).str.to_lowercase().str.contains("povidone-iodine")
)['event_full_name'].unique().to_list()

['Order - Medication__POVIDONE-IODINE 7.5 % TOPICAL SOLUTION__Antibiotics',
 'Order - Medication__POVIDONE-IODINE 10 % TOPICAL SWAB__Antibiotics',
 'Medication - Administration__POVIDONE-IODINE 10 % TOPICAL SOLN__Antibiotics',
 'Medication - Administration__POVIDONE-IODINE 10 % OINTMENT__Antibiotics',
 'Medication - Administration__POVIDONE-IODINE 10 % TOPICAL SWAB__Antibiotics',
 'Order - Medication__POVIDONE-IODINE 10 % TOPICAL SOLN__Antibiotics',
 'Order - Medication__POVIDONE-IODINE 10 % OINTMENT__Antibiotics']

In [66]:
# enc_with_antibiotic = df_all.filter(expr_antibiotics_gold_standard)['PAT_ENC_CSN_ID'].unique().to_list()
enc_with_antibiotic = df_all.filter(expr_antibiotics_gold_standard)['PAT_ENC_CSN_ID'].unique().to_list()
enc_with_culture = df_all.filter(expr_culture_orders)['PAT_ENC_CSN_ID'].unique().to_list()
enc_with_antibiotic_culture = set(enc_with_antibiotic).intersection(set(enc_with_culture))

In [74]:
df_all.filter(pl.col("Event_Grouper") == 'Antibiotics')['event_full_name'].unique().to_list()

['Order - Medication__PENICILLIN G POT IN DEXTROSE 2,000,000 UNIT/50 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__AMOXICILLIN 500 MG CAP__Antibiotics',
 'Medication - Administration__PIPERACILLIN-TAZOBACTAM-DEXTROSE (ISO) 3.375 GRAM/50 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__CHLORHEXIDINE (HIBICLENS) 4 % TOPICAL LIQUID (OR)__Antibiotics',
 'Order - Medication__DAPTOMYCIN IV PUSH__Antibiotics',
 'Medication - Administration__MUPIROCIN 2 % TOPICAL CREAM__Antibiotics',
 'Order - Medication__ERYTHROMYCIN ETHYLSUCCINATE 400 MG/5 ML SUSP, RECON__Antibiotics',
 'Order - Medication__PERITONEAL DIALYSIS MIXTURE SOLUTION__Antibiotics',
 'Order - Medication__PIPERACILLIN-TAZOBACTAM 13.5 GRAM INTRAVENOUS SOLUTION__Antibiotics',
 'Medication - Administration__AZITHROMYCIN 250 MG TAB__Antibiotics',
 'Order - Medication__AMPHOTERICIN B 50 MG SOLUTION FOR INJECTION__Antibiotics',
 'Medication - Administration__BACITRACIN ZINC-POLYMYXIN B 500 UNIT-10,000 UNIT/GRAM OINTMENT__Antibiotics',
 'Medication - Administration__PENICILLIN V POTASSIUM 125 MG/5 ML ORAL SUSP__Antibiotics',
 'Medication - Administration__PENICILLIN G BENZATHINE 2,400,000 UNIT/4 ML IM SYRINGE__Antibiotics',
 'Medication - Administration__NITROFURANTOIN (25% MACROCRYSTAL FORM) 100 MG CAP__Antibiotics',
 'Medication - Administration__TIGECYCLINE 100 MG IVPB__Antibiotics',
 'Order - Medication__NAFCILLIN 2 GRAM IV SOLUTION__Antibiotics',
 'Order - Medication__PENICILLIN V POTASSIUM 500 MG TAB__Antibiotics',
 'Order - Medication__PERITONEAL DIALYSIS ANTIBIOTIC MIXTURE SOLUTION__Antibiotics',
 'Medication - Administration__GENTAMICIN IN SALINE (ISO-OSMOTIC) 80 MG/50 ML IV PIGGY BACK (ACTUAL BODY WEIGHT)__Antibiotics',
 'Order - Medication__AMOXICILLIN-POT CLAVULANATE 250 MG-125 MG TAB__Antibiotics',
 'Medication - Administration__PIPERACILLIN-TAZOBACTAM (ZOSYN) 4.5 G IN D5W ADD-VANTAGE 50 ML (VIAL2BAG MIXTURE)__Antibiotics',
 'Medication - Administration__VANCOMYCIN 2 GRAM/500 ML IN 0.9 % SODIUM CHLORIDE INTRAVENOUS__Antibiotics',
 'Order - Medication__AMOXICILLIN-POT CLAVULANATE 400 MG-57 MG/5 ML ORAL SUSP__Antibiotics',
 'Order - Medication__METRONIDAZOLE IN SODIUM CHLORIDE (ISO-OSM) 500 MG/100 ML IV PIGGY BACK__Antibiotics',
 'Medication - Administration__AMOXICILLIN-POT CLAVULANATE 250 MG-62.5 MG/5 ML ORAL SUSP__Antibiotics',
 'Medication - Administration__VANCOMYCIN 2.5 MG/ML-HEPARIN 2,500 UNITS/ML (LOCK, HD)__Antibiotics',
 'Order - Medication__ERYTHROMYCIN 500 MG TAB, DELAYED RELEASE__Antibiotics',
 'Medication - Administration__CEFADROXIL 500 MG CAP__Antibiotics',
 'Order - Medication__VANCOMYCIN IV 1750 MG (VIAL2BAG MIXTURE)__Antibiotics',
 'Medication - Administration__DOXYCYCLINE 100 MG IVPB (VIAL2BAG)__Antibiotics',
 'Order - Medication__VANCOMYCIN 750 MG IVPB IN NS/D5W (VIAL2BAG)__Antibiotics',
 'Medication - Administration__DAPTOMYCIN IV PUSH__Antibiotics',
 'Medication - Administration__IDARUBICIN CHEMO INFUSION__Antibiotics',
 'Order - Medication__VANCOMYCIN IV 1500 MG (VIAL2BAG MIXTURE)__Antibiotics',
 'Medication - Administration__CHLORHEXIDINE GLUCONATE 2 % TOWELETTE__Antibiotics',
 'Order - Medication__BACITRACIN ZINC-POLYMYXIN B 500 UNIT-10,000 UNIT/GRAM OINTMENT__Antibiotics',
 'Order - Medication__POVIDONE-IODINE 7.5 % TOPICAL SOLUTION__Antibiotics',
 'Order - Medication__CEFTRIAXONE 2 GM IVPB (MINIBAG PLUS)__Antibiotics',
 'Medication - Administration__CEFTAZIDIME-AVIBACTAM (AVYCAZ) 2.5G IN NS 100ML (MINIBAG PLUS)__Antibiotics',
 'Order - Medication__CLINDAMYCIN 1 % TOPICAL SOLN__Antibiotics',
 'Order - Medication__PIPERACILLIN-TAZOBACTAM 4.5 GM IVPB IN D5W__Antibiotics',
 'Order - Medication__VANCOMYCIN 1.25 GRAM INTRAVENOUS SOLUTION__Antibiotics',
 'Medication - Administration__GENTAMICIN 0.3 % EYE DROPS__Antibiotics',
 'Order - Medication__AMPHOTERICIN B LIPOSOME IVPB__Antibiotics',
 'Order - Medication__MOXIFLOXACIN 400 MG TAB__Antibiotics',
 'Medication - Administration__NEOMYCIN-BACITRACN ZN-POLYMYXIN 3.5 MG-400 UNIT-5,000 UNIT/G OINTMENT__Antibiotics',
 'Order - Medication__BACITRACIN 500 UNIT/G OINTMENT__Antibiotics',
 'Order - Medication__DOXYCYCLINE MONOHYDRATE ORAL__Antibiotics',
 'Order - Medication__ANIDULAFUNGIN 100 MG IV SOLUTION__Antibiotics',
 'Order - Medication__VANCOMYCIN 750 MG INTRAVENOUS SOLUTION__Antibiotics',
 'Order - Medication__IMIPENEM-CILASTATIN 250 MG IV SOLUTION__Antibiotics',
 'Medication - Administration__ERTAPENEM  1 G IV PUSH__Antibiotics',
 'Medication - Administration__MINOCYCLINE (MINOCIN) 100 MG/100 ML NS (MINIBAG PLUS)__Antibiotics',
 'Medication - Administration__PIPERACILLIN-TAZOBACTAM (ZOSYN) 13.5 GRAM CONTINUOUS INFUSION__Antibiotics',
 'Order - Medication__LEVOFLOXACIN IN D5W 250 MG/50 ML IV PIGGY BACK__Antibiotics',
 'Medication - Administration__CIPROFLOXACIN 250 MG TAB__Antibiotics',
 'Order - Medication__AMOXICILLIN 400 MG/5 ML ORAL SUSP__Antibiotics',
 'Order - Medication__CEFUROXIME AXETIL 500 MG TAB__Antibiotics',
 'Medication - Administration__AZTREONAM (AZACTAM) 500 MG IV PUSH__Antibiotics',
 'Order - Medication__MINOCYCLINE (MINOCIN) 100 MG/100 ML NS (MINIBAG PLUS)__Antibiotics',
 'Medication - Administration__PIPERACILLIN-TAZOBACTAM (ZOSYN) 3.375G IN D5W ADD-VANTAGE 50 ML (VIAL2BAG MIXTURE)__Antibiotics',
 'Order - Medication__IRRIGATION SOLUTIONS BUILDER__Antibiotics',
 'Order - Medication__CEFAZOLIN IV 1G IV PUSH__Antibiotics',
 'Order - Medication__ERTAPENEM 500 MG IV__Antibiotics',
 'Medication - Administration__OMADACYCLINE 150 MG TABLET__Antibiotics',
 'Medication - Administration__VANCOMYCIN 750 MG IVPB IN NS/D5W (VIAL2BAG)__Antibiotics',
 'Order - Medication__NEOMYCIN-BACITRACN ZN-POLYMYXIN 3.5 MG-400 UNIT-5,000 UNIT/G OINTMENT__Antibiotics',
 'Medication - Administration__POVIDONE IODINE IN NS IRRIGATION FOR CHEST__Antibiotics',
 'Order - Medication__PENICILLIN V POTASSIUM 250 MG/5 ML ORAL SUSP__Antibiotics',
 'Order - Medication__PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)__Antibiotics',
 'Medication - Administration__VANCOMYCIN IRRIGATION SOLUTION__Antibiotics',
 'Order - Medication__CLARITHROMYCIN 500 MG TAB__Antibiotics',
 'Order - Medication__AMOXICILLIN 500 MG TAB__Antibiotics',
 'Medication - Administration__AZTREONAM 2 G IV PUSH__Antibiotics',
 'Order - Medication__CEFTRIAXONE 1 GRAM IV SOLUTION__Antibiotics',
 'Medication - Administration__PERITONEAL DIALYSIS ANTIBIOTIC MIXTURE SOLUTION__Antibiotics',
 'Medication - Administration__PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)__Antibiotics',
 'Medication - Administration__PERITONEAL DIALYSIS MIXTURE SOLUTION__Antibiotics',
 'Order - Medication__VANCOMYCIN 50 MG/ML ORAL SOLUTION__Antibiotics',
 'Order - Medication__TOBRAMYCIN IV PULSE DOSING__Antibiotics',
 'Order - Medication__DOXYCYCLINE 100 MG TAB__Antibiotics',
 'Order - Medication__CIPROFLOXACIN 0.3 % EYE DROPS__Antibiotics',
 'Order - Medication__AMIKACIN FOR INHALATION__Antibiotics',
 'Medication - Administration__DAPTOMYCIN 500 MG IV SOLUTION__Antibiotics',
 'Medication - Administration__METRONIDAZOLE 500 MG TAB__Antibiotics',
 'Medication - Administration__TOBRAMYCIN-DEXAMETHASONE 0.3 %-0.1 % EYE DROPS, SUSP__Antibiotics',
 'Order - Medication__VANCOMYCIN 1.75 GRAM/250 ML (PF) IN 0.9 % SODIUM CHLORIDE__Antibiotics',
 'Order - Medication__TOBRAMYCIN FORTIFIED OPHTHALMIC SOLUTION__Antibiotics',
 'Order - Medication__ceFEPIme (MAXIPIME) 2 gram injection DOSE:__Antibiotics',
 'Medication - Administration__VANCOMYCIN IN DEXTROSE 500 MG/100 ML IV PIGGY BACK__Antibiotics',
 'Medication - Administration__CEFAZOLIN 1 GRAM SOLUTION FOR INJECTION__Antibiotics',
 'Medication - Administration__CLINDAMYCIN IN D5W 600 MG/50 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__IDARUBICIN CHEMO INFUSION__Antibiotics',
 'Medication - Administration__CEFAZOLIN 2 G IV PUSH__Antibiotics',
 'Order - Medication__POVIDONE IODINE IN NS IRRIGATION FOR CHEST__Antibiotics',
 'Order - Medication__AZTREONAM 2 G IV PUSH__Antibiotics',
 'Order - Medication__VANCOMYCIN 1 MG/0.1 ML INTRAVITREAL INJECTION__Antibiotics',
 'Order - Medication__CEFTIBUTEN ORAL__Antibiotics',
 'Medication - Administration__NYSTATIN 100,000 UNIT/ML ORAL SUSP__Antibiotics',
 'Order - Medication__GENTAMICIN 100 MG IN 0.9% SODIUM CHLORIDE 1000 ML IRRIGATION__Antibiotics',
 'Order - Medication__VANCOMYCIN 1,000 MG IV SOLUTION__Antibiotics',
 'Medication - Administration__LINEZOLID 600 MG TAB__Antibiotics',
 'Medication - Administration__VANCOMYCIN 1.5 GRAM/250 ML IN 0.9 % SODIUM CHLORIDE IV__Antibiotics',
 'Order - Medication__IMIPENEM-CILASTATIN-RELEBACTAM 500MG/40ML INFUSION__Antibiotics',
 'Order - Medication__CEFAZOLIN 1 GM IN 500 ML 0.9% SODIUM CHLORIDE IRRIGATION__Antibiotics',
 'Medication - Administration__IMIPENEM-CILASTATIN CUSTOM DOSE IVPB__Antibiotics',
 'Medication - Administration__AMPHOTERICIN B LIPOSOME 25 MG/6.25 ML INHALATION__Antibiotics',
 'Order - Medication__SULFAMETHOXAZOLE-TRIMETHOPRIM 800 MG-160 MG TAB__Antibiotics',
 'Order - Medication__MUPIROCIN 2 % OINTMENT__Antibiotics',
 'Order - Medication__AMPHOTERICIN B LIPOSOME 25 MG/6.25 ML INHALATION__Antibiotics',
 'Medication - Administration__LINEZOLID 100 MG/5 ML ORAL SUSP__Antibiotics',
 'Medication - Administration__SULFAMETHOXAZOLE-TRIMETHOPRIM IVPB 250 ML__Antibiotics',
 'Order - Medication__CEFEPIME 2 G IV PUSH__Antibiotics',
 'Medication - Administration__VANCOMYCIN 250 MG CAP__Antibiotics',
 'Medication - Administration__CLINDAMYCIN 75 MG/5 ML ORAL SOLUTION__Antibiotics',
 'Medication - Administration__BACITRACIN-POLYMYXIN B 500 UNIT-10,000 UNIT/G EYE OINTMENT__Antibiotics',
 'Medication - Administration__PENICILLIN V POTASSIUM 500 MG TAB__Antibiotics',
 'Medication - Administration__AZTREONAM 1 G IV PUSH__Antibiotics',
 'Order - Medication__CEFEPIME 2 GRAM/50 ML IN DEXTROSE 5 % INTRAVENOUS PIGGYBACK__Antibiotics',
 'Order - Medication__VANCOMYCIN 750 MG/150 ML IN DEXTROSE 5 % INTRAVENOUS PIGGYBACK__Antibiotics',
 'Medication - Administration__CEFPODOXIME 200 MG TAB__Antibiotics',
 'Order - Medication__DAPTOMYCIN 1,000 MG/100 ML IN 0.9 % SODIUM CHLOR INTRAVENOUS PIGGYBACK__Antibiotics',
 'Order - Medication__AMIKACIN IVPB__Antibiotics',
 'Order - Medication__AMOXICILLIN-POT CLAVULANATE 125 MG-31.25 MG/5 ML ORAL SUSP__Antibiotics',
 'Order - Medication__BACITRACIN ZINC 500 UNIT-POLYMYXIN B 10,000 UNIT/GRAM TOP OINT PACKET__Antibiotics',
 'Order - Medication__LEVOFLOXACIN 250 MG/10 ML ORAL SOLN__Antibiotics',
 'Medication - Administration__TOBRAMYCIN FORTIFIED OPHTHALMIC SOLUTION__Antibiotics',
 'Order - Medication__MEROPENEM 500 MG IV PUSH__Antibiotics',
 'Order - Medication__VANCOMYCIN (VANCOCIN) FOR STERNAL PASTE__Antibiotics',
 'Medication - Administration__DOXORUBICIN CHEMO INFUSION__Antibiotics',
 'Medication - Administration__DOXYCYCLINE 200 MG IVPB__Antibiotics',
 'Medication - Administration__CEFAZOLIN IV 1G IV PUSH__Antibiotics',
 'Order - Medication__AMIKACIN IV PULSE DOSING__Antibiotics',
 'Medication - Administration__PENICILLIN V POTASSIUM 250 MG/5 ML ORAL SUSP__Antibiotics',
 'Medication - Administration__VANCOMYCIN 500 MG IN NS 100 ML (MINIBAG PLUS)__Antibiotics',
 'Medication - Administration__AMOXICILLIN-POT CLAVULANATE 500 MG-125 MG TAB__Antibiotics',
 'Medication - Administration__GENTAMICIN 0.1 % OINTMENT__Antibiotics',
 'Medication - Administration__CEPHALEXIN 500 MG CAP__Antibiotics',
 'Order - Medication__EPOCH CHEMO INFUSION__Antibiotics',
 'Order - Medication__TIGECYCLINE 100 MG IVPB__Antibiotics',
 'Order - Medication__AMIKACIN 250 MG/500 ML BLADDER RINSE SOLUTION__Antibiotics',
 'Medication - Administration__RIFAPENTINE 150 MG TAB__Antibiotics',
 'Order - Medication__CLINDAMYCIN IN D5W 900 MG/50 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__VANCOMYCIN 1 GRAM/200 ML IN 0.9 % SOD. CHLORIDE INTRAVENOUS PIGGYBACK__Antibiotics',
 'Order - Medication__GENTAMICIN IN SALINE (ISO-OSMOTIC) 60 MG/50 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__METRONIDAZOLE 50 MG/ML ORAL SUSPENSION__Antibiotics',
 'Medication - Administration__TOBRAMYCIN-DEXAMETHASONE 0.3 %-0.1 % EYE OINTMENT__Antibiotics',
 'Order - Medication__VANCOMYCIN 2 G IN 500 ML (VIAL2BAG MIXTURE)__Antibiotics',
 'Order - Medication__AMPICILLIN-SULBACTAM IN NS 3 GM IVPB__Antibiotics',
 'Medication - Administration__NEOMYCIN-POLYMYXIN-HC 3.5 MG-10,000 UNIT-10 MG/ML EYE DROPS, SUSP__Antibiotics',
 'Order - Medication__CEFAZOLIN 1 G IRRIGATION SOLUTION  0.5 L__Antibiotics',
 'Order - Medication__RIFAPENTINE 150 MG TAB__Antibiotics',
 'Medication - Administration__BACITRACIN ZINC 500 UNIT-POLYMYXIN B 10,000 UNIT/GRAM TOP OINT PACKET__Antibiotics',
 'Medication - Administration__OFLOXACIN 0.3 % EAR DROPS__Antibiotics',
 'Order - Medication__PENICILLIN G POTASSIUM IVPB 4 MILLION UNITS/100 ML D5W__Antibiotics',
 'Order - Medication__CEFEPIME 2 GM IVPB__Antibiotics',
 'Order - Medication__PENICILLIN G POTASSIUM CUSTOM DOSE IVPB__Antibiotics',
 'Order - Medication__AZITHROMYCIN 600 MG TAB__Antibiotics',
 'Order - Medication__CEFAZOLIN IN DEXTROSE (ISO-OSMOTIC) 2 GRAM/50 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__BEZLOTOXUMAB INFUSION__Antibiotics',
 'Order - Medication__CEFIDEROCOL 1 GRAM INTRAVENOUS SOLUTION__Antibiotics',
 'Order - Medication__CIPROFLOXACIN 750 MG TAB__Antibiotics',
 'Order - Medication__CEFTRIAXONE 2 G IV PUSH__Antibiotics',
 'Medication - Administration__CEFTRIAXONE 1 GRAM SOLUTION FOR INJECTION__Antibiotics',
 'Order - Medication__CEFAZOLIN 1 GRAM SOLUTION FOR INJECTION__Antibiotics',
 'Order - Medication__PIPERACILLIN-TAZOBACTAM (ZOSYN) 2.25 G IV PUSH__Antibiotics',
 'Order - Medication__VANCOMYCIN IN DEXTROSE 500 MG/100 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__NITROFURANTOIN (25% MACROCRYSTAL FORM) 100 MG CAP__Antibiotics',
 'Order - Medication__PIPERACILLIN-TAZOBACTAM 3.375 GM IVPB IN NS__Antibiotics',
 'Medication - Administration__TOBRAMYCIN 1.2 G SOLUTION FOR INJECTION__Antibiotics',
 'Order - Medication__CEFAZOLIN 2 G IV PUSH__Antibiotics',
 'Order - Medication__TOBRAMYCIN 300 MG/5 ML NEB SOLUTION__Antibiotics',
 'Order - Medication__GENTAMICIN 0.3 % EYE DROPS__Antibiotics',
 'Order - Medication__AMOXICILLIN 250 MG CAP__Antibiotics',
 'Order - Medication__NEOMYCIN-BACITRACIN-POLY-HC 3.5 MG-400-10,000 UNIT/G-1 % EYE OINTMENT__Antibiotics',
 'Order - Medication__AMPICILLIN-SULBACTAM 1.5G IN NS 100 ML (MINIBAG PLUS)__Antibiotics',
 'Medication - Administration__DOXYCYCLINE 100 MG CAP__Antibiotics',
 'Medication - Administration__CEFAZOLIN 3 G IV PUSH__Antibiotics',
 'Order - Medication__VANCOMYCIN 1.25 GRAM/250 ML IN 0.9 % SODIUM CHLORIDE IV__Antibiotics',
 'Order - Medication__NYSTATIN 100,000 UNIT/ML ORAL SUSP__Antibiotics',
 'Order - Medication__MUPIROCIN 2 % TOPICAL CREAM__Antibiotics',
 'Medication - Administration__IMIPENEM-CILASTATIN 1 GM IVPB__Antibiotics',
 'Order - Medication__CEFTAZIDIME IN NS 500 ML CONTINUOUS INFUSION__Antibiotics',
 'Medication - Administration__VANCOMYCIN 500 MG IV SOLUTION__Antibiotics',
 'Order - Medication__CEFPODOXIME 100 MG TAB__Antibiotics',
 'Medication - Administration__CEFTOLOZANE-TAZOBACTAM IN NS IVPB__Antibiotics',
 'Medication - Administration__VANCOMYCIN 1 G IN 0.9% SODIUM CHLORIDE 500 ML IRRIGATION__Antibiotics',
 'Order - Medication__ERYTHROMYCIN IVPB__Antibiotics',
 'Order - Medication__VANCOMYCIN 1 GM IN D5W 200 ML IVPB__Antibiotics',
 'Order - Medication__NEOMYCIN-POLYMYXIN-DEXAMETH 3.5 MG-10,000 UNIT/G-0.1 % EYE OINTMENT__Antibiotics',
 'Medication - Administration__VANCOMYCIN 1 MG/0.1 ML INTRAVITREAL INJECTION__Antibiotics',
 'Medication - Administration__PERITONEAL DIALYSIS SOLUTION WITH HEPARIN - CYCLER__Antibiotics',
 'Medication - Administration__VANCOMYCIN 50 MG/ML ORAL SOLUTION__Antibiotics',
 'Medication - Administration__POVIDONE-IODINE 10 % OINTMENT__Antibiotics',
 'Order - Medication__CEFADROXIL 1 GRAM TAB__Antibiotics',
 'Order - Medication__MICAFUNGIN 100MG IN NS 100ML (MINIBAG PLUS)__Antibiotics',
 'Order - Medication__IMIPENEM-CILASTATIN-RELEBACTAM 1.25 GRAM INTRAVENOUS SOLUTION__Antibiotics',
 'Medication - Administration__VANCOMYCIN 2 G IN 500 ML (VIAL2BAG MIXTURE)__Antibiotics',
 'Order - Medication__AMPHOTERICIN B LIPID COMPLEX 5 MG/ML IV__Antibiotics',
 'Order - Medication__LINEZOLID 100 MG/5 ML ORAL SUSP__Antibiotics',
 'Order - Medication__TOBRAMYCIN 1.2 G SOLUTION FOR INJECTION__Antibiotics',
 'Order - Medication__MITOMYCIN IN NS FOR HIPEC PROCEDURE__Antibiotics',
 'Order - Medication__VANCOMYCIN 1.5 GRAM INTRAVENOUS SOLUTION__Antibiotics',
 'Medication - Administration__SULFAMETHOXAZOLE-TRIMETHOPRIM 800 MG-160 MG TAB__Antibiotics',
 'Order - Medication__VANCOMYCIN 25 MG/ML OPHTHALMIC SOLUTION__Antibiotics',
 'Medication - Administration__AMIKACIN IVPB__Antibiotics',
 'Order - Medication__DOXORUBICIN CHEMO INFUSION__Antibiotics',
 'Order - Medication__BACITRACIN-POLYMYXIN B 500 UNIT-10,000 UNIT/G EYE OINTMENT__Antibiotics',
 'Medication - Administration__GENTAMICIN 40 MG/ML INJECTION__Antibiotics',
 'Order - Medication__VANCOMYCIN 250 MG/5 ML ORAL SOLUTION__Antibiotics',
 'Medication - Administration__NEOMYCIN-POLYMYXIN-DEXAMETH 3.5 MG-10,000 UNIT/G-0.1 % EYE OINTMENT__Antibiotics',
 'Order - Medication__AZITHROMYCIN 250 MG IVPB __Antibiotics',
 'Order - Medication__AMPHOTERICIN B LIPOSOME 2.5 MG/ML ANTIFUNGAL LOCK SOLUTION IN D5W__Antibiotics',
 'Order - Medication__KITABIS PAK 300 MG/5 ML SOLUTION FOR NEBULIZATION__Antibiotics',
 'Medication - Administration__DAUNORUBICIN CHEMO INFUSION__Antibiotics',
 'Order - Medication__TOBRAMYCIN-DEXAMETHASONE 0.3 %-0.1 % EYE DROPS, SUSP__Antibiotics',
 'Medication - Administration__METRONIDAZOLE 50 MG/ML ORAL SUSPENSION__Antibiotics',
 'Order - Medication__VANCOMYCIN 500 MG IV SOLUTION__Antibiotics',
 'Order - Medication__CLINDAMYCIN 75 MG/5 ML ORAL SOLUTION__Antibiotics',
 'Order - Medication__PIPERACILLIN-TAZOBACTAM (ZOSYN) 4.5 G IN D5W ADD-VANTAGE 50 ML (VIAL2BAG MIXTURE)__Antibiotics',
 'Medication - Administration__AZITHROMYCIN 250 MG IVPB __Antibiotics',
 'Medication - Administration__AMOXICILLIN 250 MG/5 ML ORAL SUSP__Antibiotics',
 'Medication - Administration__RIFAMPIN 600MG IN NS 100ML (VIAL2BAG MIXTURE)__Antibiotics',
 'Order - Medication__CEFIXIME 400 MG CAPSULE__Antibiotics',
 'Order - Medication__SULFAMETHOXAZOLE-TRIMETHOPRIM 400 MG-80 MG TAB__Antibiotics',
 'Order - Medication__VANCOMYCIN 500 MG IN NS 100 ML (MINIBAG PLUS)__Antibiotics',
 'Order - Medication__VANCOMYCIN 1,750 MG IVPB__Antibiotics',
 'Medication - Administration__PIPERACILLIN-TAZOBACTAM 3.375G IVPB (MINIBAG PLUS)__Antibiotics',
 'Order - Medication__NAFCILLIN 2G IN NS 100 ML (MINIBAG PLUS)__Antibiotics',
 'Order - Medication__CIPROFLOXACIN IN D5W 400 MG/200 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__CEFTRIAXONE 1 GRAM SOLUTION FOR INJECTION__Antibiotics',
 'Medication - Administration__MEROPENEM 2 G IVPB__Antibiotics',
 'Order - Medication__SULFAMETHOXAZOLE-TRIMETHOPRIM IVPB 100 ML__Antibiotics',
 'Order - Medication__TOBRAMYCIN WITH NEBULIZER 300 MG/5 ML SOLUTION FOR NEBULIZATION__Antibiotics',
 'Medication - Administration__CEFAZOLIN 2 GM IVPB__Antibiotics',
 'Order - Medication__CIPROFLOXACIN 100 MG TAB__Antibiotics',
 'Medication - Administration__LEVOFLOXACIN 500 MG TAB__Antibiotics',
 'Medication - Administration__CEFAZOLIN-GENTAMICIN 1 G-80 MG IN NS 500 ML SOLUTION FOR OR__Antibiotics',
 'Order - Medication__AMOXICILLIN-POT CLAVULANATE 600 MG-42.9 MG/5 ML ORAL SUSP__Antibiotics',
 'Medication - Administration__VANCOMYCIN IN DEXTROSE 1 GRAM/200 ML IV PIGGY BACK__Antibiotics',
 'Order - Medication__ERYTHROMYCIN 5 MG/G EYE OINTMENT__Antibiotics',
 'Medication - Administration__MICAFUNGIN 100MG IN NS 100ML (MINIBAG PLUS)__Antibiotics',
 'Medication - Administration__VANCOMYCIN IV 1500 MG (VIAL2BAG MIXTURE)__Antibiotics',
 'Medication - Administration__MINOCYCLINE 100 MG CAP__Antibiotics',
 'Order - Medication__TOBRAMYCIN 300 MG/4 ML SOLUTION FOR NEBULIZATION__Antibiotics',
 'Order - Medication__AMPICILLIN IV 2G IN NS 100 ML (MINIBAG PLUS)__Antibiotics',

In [72]:
df_all.filter(pl.col("PAT_ENC_CSN_ID") == 727717399)

shape: (1_560, 25)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ PAT_ENC_C ┆ PAT_MRN_I ┆ PAT_ID   ┆ Ethnicity ┆ … ┆ MEAS_VALU ┆ Sepsis_Ca ┆ FLAG_DEAT ┆ event_ful │
│ SN_ID     ┆ D         ┆ ---      ┆ ---       ┆   ┆ E         ┆ tegory    ┆ H_CLARITY ┆ l_name    │
│ ---       ┆ ---       ┆ str      ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆ i64       ┆          ┆           ┆   ┆ str       ┆ str       ┆ i64       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ null      ┆ NPOA-3    ┆ 0         ┆ Diagnosis │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ Audit -   │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ Add__Chol │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ang…      │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ null      ┆ NPOA-3    ┆ 0         ┆ Order -   │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ Medicatio │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ n__ACETAM │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ INOP…     │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ 16        ┆ NPOA-3    ┆ 0         ┆ Flowsheet │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ __RESPIRA │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ TIONS__Re │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ spi…      │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ 181/87    ┆ NPOA-3    ┆ 0         ┆ Flowsheet │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ __BLOOD   │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ PRESSURE_ │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ _Blo…     │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ 97.9      ┆ NPOA-3    ┆ 0         ┆ Flowsheet │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ __TEMPERA │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ TURE__Tem │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ per…      │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ 55        ┆ NPOA-3    ┆ 0         ┆ Flowsheet │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ __PULSE__ │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ Pulse     │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ 97.9      ┆ NPOA-3    ┆ 0         ┆ Flowsheet │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ __TEMPERA │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ TURE__Tem │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ per…      │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ 1         ┆ NPOA-3    ┆ 0         ┆ Flowsheet │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ __UTSW UH │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ R UNMEASU │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ RE…       │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ 1         ┆ NPOA-3    ┆ 0         ┆ Flowsheet │
│           ┆           ┆          ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ __UTSW UH │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ R UNMEASU │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ RE…       │
│ 727717399 ┆ 93320420  ┆ Z5778919 ┆ Non-Hispa ┆ … ┆ No growth ┆ NPOA-3    ┆ 0         ┆ Order     │
│           ┆           ┆          ┆ nic/Latin ┆   ┆ at 5 Days ┆           ┆           ┆ Result -  │
│           ┆           ┆          ┆ o         ┆   ┆           ┆           ┆           ┆ Microbiol │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ogy__C…   │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
set(npoa3_enc)-set(enc_with_antibiotic)

NameError: name 'npoa3_enc' is not defined

In [69]:

df_all.filter(pl.col("PAT_ENC_CSN_ID").is_in(
    set(npoa3_enc)-set(enc_with_antibiotic)
)).group_by("PAT_ENC_CSN_ID").agg(pl.len().alias('count'),  pl.col("Pt_Arrival").first(), pl.col("Event_DateTime").last(), pl.col("Patient_Age").last()).with_columns(
    (pl.col("Event_DateTime")-pl.col("Pt_Arrival")).dt.total_days()
)

shape: (11, 5)
┌────────────────┬───────┬─────────────────────┬────────────────┬─────────────┐
│ PAT_ENC_CSN_ID ┆ count ┆ Pt_Arrival          ┆ Event_DateTime ┆ Patient_Age │
│ ---            ┆ ---   ┆ ---                 ┆ ---            ┆ ---         │
│ i64            ┆ u64   ┆ datetime[ns]        ┆ i64            ┆ f64         │
╞════════════════╪═══════╪═════════════════════╪════════════════╪═════════════╡
│ 727717399      ┆ 1560  ┆ 2025-05-19 12:28:48 ┆ 12             ┆ 70.206707   │
│ 729299844      ┆ 4071  ┆ 2025-06-11 15:15:00 ┆ 21             ┆ 60.303901   │
│ 722093996      ┆ 3874  ┆ 2025-02-25 05:55:00 ┆ 55             ┆ 80.043805   │
│ 722181771      ┆ 1526  ┆ 2025-02-25 17:44:00 ┆ 16             ┆ 79.047227   │
│ 722561454      ┆ 998   ┆ null                ┆ null           ┆ 38.696783   │
│ …              ┆ …     ┆ …                   ┆ …              ┆ …           │
│ 732141379      ┆ 1903  ┆ 2025-07-26 14:51:00 ┆ 15             ┆ 71.101984   │
│ 728885185      ┆ 969   ┆ 2025-06-09 09:05:38 ┆ 6              ┆ 59.255304   │
│ 728630643      ┆ 1576  ┆ 2025-06-03 03:17:58 ┆ 11             ┆ 72.238193   │
│ 722523701      ┆ 5983  ┆ 2025-03-03 13:23:00 ┆ 23             ┆ 67.583846   │
│ 724267617      ┆ 5229  ┆ 2025-04-07 08:36:39 ┆ 47             ┆ 58.518822   │
└────────────────┴───────┴─────────────────────┴────────────────┴─────────────┘

In [64]:
df_all.filter(pl.col("PAT_ENC_CSN_ID") == 723816642)

shape: (4_141, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ PAT_ENC_C ┆ PAT_MRN_I ┆ PAT_ID    ┆ Ethnicity ┆ … ┆ MEAS_VALU ┆ Sepsis_Ca ┆ FLAG_DEAT ┆ event_fu │
│ SN_ID     ┆ D         ┆ ---       ┆ ---       ┆   ┆ E         ┆ tegory    ┆ H_CLARITY ┆ ll_name  │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆           ┆           ┆   ┆ str       ┆ str       ┆ i64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ 15        ┆ NPOA-3    ┆ 0         ┆ Flowshee │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ t__CPM   │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ S24 R AS │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ SC GLA…  │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ 3360      ┆ NPOA-3    ┆ 0         ┆ Flowshee │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ t__WEIGH │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ T/SCALE_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _Weigh…  │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ 122/60    ┆ NPOA-3    ┆ 0         ┆ Flowshee │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ t__BLOOD │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ PRESSURE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ __Blo…   │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ 81        ┆ NPOA-3    ┆ 0         ┆ Flowshee │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ t__PULSE │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ __Pulse  │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ 98.4      ┆ NPOA-3    ┆ 0         ┆ Flowshee │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ t__TEMPE │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ RATURE__ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Temper…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ 120/53    ┆ NPOA-3    ┆ 0         ┆ Flowshee │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ t__BLOOD │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ PRESSURE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ __Blo…   │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ 88        ┆ NPOA-3    ┆ 0         ┆ Flowshee │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ t__PULSE │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ __Pulse  │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ 18        ┆ NPOA-3    ┆ 0         ┆ Flowshee │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ t__RESPI │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ RATIONS_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _Respi…  │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ null      ┆ NPOA-3    ┆ 0         ┆ Order -  │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ Medicati │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ on__ONDA │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ NSETRO…  │
│ 723816642 ┆ 98781967  ┆ Z11241318 ┆ Non-Hispa ┆ … ┆ null      ┆ NPOA-3    ┆ 0         ┆ Order -  │
│           ┆           ┆           ┆ nic/Latin ┆   ┆           ┆           ┆           ┆ Medicati │
│           ┆           ┆           ┆ o         ┆   ┆           ┆           ┆           ┆ on__BACI │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ TRACIN…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [62]:
set(npoa3_enc)-set(enc_with_antibiotic_culture)

{723816642}

In [58]:
df_all.filter(pl.col("PAT_ENC_CSN_ID")==722093996).filter(pl.col("Event_Grouper")=='Antibiotics')['EVENT_NAME'].to_list()

['MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'MUPIROCIN 2 % OINTMENT',
 'PIPERACILLIN-TAZOBACTAM 3.375G IVPB (MINIBAG PLUS)',
 'LINEZOLID 600 MG/300 ML IV',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'LINEZOLID 600 MG/300 ML IV',
 'LINEZOLID 600 MG/300 ML IV',
 'MUPIROCIN 2 % OINTMENT',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'LINEZOLID 600 MG/300 ML IV',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)',
 'PIPERACILLIN-TAZOBACTAM 4.5G IVPB (MINIBAG PLUS)']

In [44]:
enc_with_antibiotic_culture = df_all.filter(expr_antibiotics_gold_standard& expr_culture_orders)['PAT_ENC_CSN_ID'].unique()

In [46]:
len(npoa3_enc)

313

In [45]:
LEN(set(npoa3_enc) - set(enc_with_antibiotic_culture)

{695960811,
 697718727,
 699476058,
 705630549,
 708553079,
 709516764,
 710566991,
 711219567,
 711291066,
 711634600,
 711743163,
 712736291,
 712990475,
 713249637,
 713494393,
 713754181,
 713809904,
 713896995,
 713986813,
 714258072,
 714258471,
 714349177,
 714356035,
 714398067,
 714534044,
 714658799,
 714670948,
 714679392,
 714738435,
 714800085,
 714871212,
 714872125,
 714901045,
 714936647,
 715080844,
 715131999,
 715178956,
 715206321,
 715261758,
 715278022,
 715675849,
 715683762,
 715936275,
 715961369,
 716057615,
 716112176,
 716155089,
 716170408,
 716208986,
 716230893,
 716254313,
 716378803,
 716386924,
 716426887,
 716513136,
 716522133,
 716603434,
 716629145,
 716745079,
 716791205,
 716791386,
 716802228,
 716826509,
 716828653,
 716907686,
 717006646,
 717036079,
 717138018,
 717187915,
 717264691,
 717438884,
 717452217,
 717576078,
 717740076,
 717767063,
 717856271,
 717937894,
 718016274,
 718021638,
 718022292,
 718092252,
 718200023,
 718334950,
 718336676,
 718395065,
 718396565,
 718455692,
 718462042,
 718475188,
 718478059,
 718479327,
 718557295,
 718605628,
 718659290,
 718783901,
 718838694,
 719022604,
 719032191,
 719183819,
 719218211,
 719331363,
 719346803,
 719382168,
 719605015,
 719719663,
 719730073,
 719737048,
 719828146,
 719913308,
 720042472,
 720119493,
 720121794,
 720173512,
 720182524,
 720393222,
 720654350,
 720741720,
 720941743,
 721070054,
 721087584,
 721248395,
 721437176,
 721446830,
 721468840,
 721526717,
 721708098,
 721834933,
 721861163,
 721917627,
 721977886,
 722086381,
 722093996,
 722181771,
 722397341,
 722438431,
 722443461,
 722450737,
 722523701,
 722560549,
 722561454,
 722642762,
 722697899,
 722735094,
 722791465,
 722803504,
 722988641,
 722993607,
 723191059,
 723196801,
 723371989,
 723459334,
 723464649,
 723561764,
 723563529,
 723718914,
 723735641,
 723756174,
 723803882,
 723808769,
 723816642,
 723870857,
 723913607,
 723929922,
 724063795,
 724091454,
 724156851,
 724267617,
 724275939,
 724283134,
 724335688,
 724434406,
 724486363,
 724595891,
 724700047,
 724792936,
 724853443,
 724857296,
 724917016,
 724924492,
 725039766,
 725186139,
 725334698,
 725390246,
 725428715,
 725449150,
 725663109,
 725782942,
 725870283,
 725892942,
 725960018,
 725973116,
 726150088,
 726154894,
 726196220,
 726344130,
 726441254,
 726528293,
 726546919,
 726578688,
 726612880,
 726618009,
 726668725,
 726688590,
 726712642,
 726903689,
 726917633,
 727061532,
 727190309,
 727203058,
 727203265,
 727441497,
 727449603,
 727677245,
 727717399,
 727759587,
 727859560,
 727947276,
 728019014,
 728105178,
 728134737,
 728149000,
 728330507,
 728526767,
 728630316,
 728630643,
 728725072,
 728885185,
 728890006,
 728989317,
 729001012,
 729001558,
 729210984,
 729299844,
 729573085,
 729590295,
 729590932,
 729594194,
 729597173,
 729777794,
 729874390,
 730094775,
 730131890,
 730188914,
 730302115,
 730358732,
 730383984,
 730533875,
 730609275,
 730724597,
 730742926,
 730749227,
 730856967,
 730876376,
 730899341,
 730913233,
 731030708,
 731117579,
 731210806,
 731647023,
 731666269,
 731690730,
 731730992,
 731838185,
 731844370,
 731882102,
 732057888,
 732121960,
 732141379,
 732149250,
 732504645,
 732507684,
 732528585,
 732593318,
 732743596,
 732799198,
 732843854,
 732864687,
 732980027,
 733066424,
 733325970,
 733446658,
 733547774,
 733883850,
 733901069,
 733908128,
 733985981,
 734007300,
 734102049,
 734129832,
 734131334,
 734640640,
 734719161,
 734731034,
 734735638,
 734783879,
 734834356,
 734874042,
 735007104,
 735015191,
 735087480,
 735215078,
 735322910,
 735841555,
 735902196,
 736530151,
 736804579,
 736903797,
 737260505,
 737512191,
 737516747,
 737760571,
 737969814,
 738237217}

In [28]:
npoa3_enc = df_all.filter((pl.col("Sepsis_Category") == 'NPOA-3')['PAT_ENC_CSN_ID'].unique().to_list()

In [30]:
suspected_enc = df_suspected_infection['PAT_ENC_CSN_ID'].unique().to_list()

In [ ]:
pl

In [31]:
set(npoa3_enc)-set(suspected_enc)

{721526717,
 722093996,
 722181771,
 722523701,
 722561454,
 723816642,
 724267617,
 727717399,
 728630643,
 728885185,
 729299844,
 732141379,
 732504645}

In [63]:
df_all.filter(pl.col("PAT_ENC_CSN_ID").is_in(
    (set(npoa3_enc)-set(suspected_enc)).union({723816642})
)).group_by("PAT_ENC_CSN_ID").agg(pl.len().alias('count'),  pl.col("Pt_Arrival").first(), pl.col("Event_DateTime").last()).with_columns(
    (pl.col("Event_DateTime")-pl.col("Pt_Arrival")).dt.total_days()
)

shape: (13, 4)
┌────────────────┬───────┬─────────────────────┬────────────────┐
│ PAT_ENC_CSN_ID ┆ count ┆ Pt_Arrival          ┆ Event_DateTime │
│ ---            ┆ ---   ┆ ---                 ┆ ---            │
│ i64            ┆ u64   ┆ datetime[ns]        ┆ i64            │
╞════════════════╪═══════╪═════════════════════╪════════════════╡
│ 728885185      ┆ 969   ┆ 2025-06-09 09:05:38 ┆ 6              │
│ 729299844      ┆ 4071  ┆ 2025-06-11 15:15:00 ┆ 21             │
│ 728630643      ┆ 1576  ┆ 2025-06-03 03:17:58 ┆ 11             │
│ 722561454      ┆ 998   ┆ null                ┆ null           │
│ 721526717      ┆ 2274  ┆ 2025-02-15 00:43:26 ┆ 20             │
│ …              ┆ …     ┆ …                   ┆ …              │
│ 723816642      ┆ 4141  ┆ 2025-03-23 17:10:00 ┆ 38             │
│ 722093996      ┆ 3874  ┆ 2025-02-25 05:55:00 ┆ 55             │
│ 732504645      ┆ 10450 ┆ 2025-07-31 15:35:00 ┆ 48             │
│ 722181771      ┆ 1526  ┆ 2025-02-25 17:44:00 ┆ 16             │
│ 727717399      ┆ 1560  ┆ 2025-05-19 12:28:48 ┆ 12             │
└────────────────┴───────┴─────────────────────┴────────────────┘

In [34]:
df_all.filter(pl.col("PAT_ENC_CSN_ID").is_in(
    set(npoa3_enc)-set(suspected_enc)
)).sort(by=['PAT_ENC_CSN_ID', 'Event_DateTime']).select(
    "PAT_ENC_CSN_ID", "Pt_Arrival", 'Admit_Time', 'Event_DateTime', 'EVENT_NAME'
)

shape: (44_554, 5)
┌────────────────┬──────────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│ PAT_ENC_CSN_ID ┆ Pt_Arrival   ┆ Admit_Time           ┆ Event_DateTime      ┆ EVENT_NAME          │
│ ---            ┆ ---          ┆ ---                  ┆ ---                 ┆ ---                 │
│ i64            ┆ datetime[ns] ┆ datetime[ns]         ┆ datetime[ns]        ┆ str                 │
╞════════════════╪══════════════╪══════════════════════╪═════════════════════╪═════════════════════╡
│ 721526717      ┆ 2025-02-15   ┆ 2025-02-15 03:33:36  ┆ 2025-02-15 03:40:00 ┆ PULSE               │
│                ┆ 00:43:26     ┆                      ┆                     ┆                     │
│ 721526717      ┆ 2025-02-15   ┆ 2025-02-15 03:33:36  ┆ 2025-02-15 03:40:00 ┆ RESPIRATIONS        │
│                ┆ 00:43:26     ┆                      ┆                     ┆                     │
│ 721526717      ┆ 2025-02-15   ┆ 2025-02-15 03:33:36  ┆ 2025-02-15 03:40:00 ┆ BLOOD PRESSURE      │
│                ┆ 00:43:26     ┆                      ┆                     ┆                     │
│ 721526717      ┆ 2025-02-15   ┆ 2025-02-15 03:33:36  ┆ 2025-02-15 03:40:00 ┆ WEIGHT/SCALE        │
│                ┆ 00:43:26     ┆                      ┆                     ┆                     │
│ 721526717      ┆ 2025-02-15   ┆ 2025-02-15 03:33:36  ┆ 2025-02-15 03:40:00 ┆ MODEL R BMI         │
│                ┆ 00:43:26     ┆                      ┆                     ┆                     │
│ …              ┆ …            ┆ …                    ┆ …                   ┆ …                   │
│ 732504645      ┆ 2025-07-31   ┆ 2025-07-31 22:56:00  ┆ 2025-09-17 17:58:00 ┆ RESPIRATIONS        │
│                ┆ 15:35:00     ┆                      ┆                     ┆                     │
│ 732504645      ┆ 2025-07-31   ┆ 2025-07-31 22:56:00  ┆ 2025-09-17 17:58:00 ┆ BLOOD PRESSURE      │
│                ┆ 15:35:00     ┆                      ┆                     ┆                     │
│ 732504645      ┆ 2025-07-31   ┆ 2025-07-31 22:56:00  ┆ 2025-09-17 18:00:00 ┆ CPM S24 R INV       │
│                ┆ 15:35:00     ┆                      ┆                     ┆ DEVICE (OXYGEN T…   │
│ 732504645      ┆ 2025-07-31   ┆ 2025-07-31 22:56:00  ┆ 2025-09-17 18:00:00 ┆ RESPIRATIONS        │
│                ┆ 15:35:00     ┆                      ┆                     ┆                     │
│ 732504645      ┆ 2025-07-31   ┆ 2025-07-31 22:56:00  ┆ 2025-09-17 18:00:00 ┆ BLOOD PRESSURE      │
│                ┆ 15:35:00     ┆                      ┆                     ┆                     │
└────────────────┴──────────────┴──────────────────────┴─────────────────────┴─────────────────────┘

# SOFA score calculations

In [21]:
lf = lf.with_columns(
    pl.col("MEAS_VALUE")
    .str.extract(r"(-?\d+\.?\d*)", 1) # Regex to capture integer or float
    .cast(pl.Float64)
    .alias("val_numeric")
)

In [22]:
lf = lf.with_columns(
    pl.col("MEAS_VALUE")
    .str.extract(r"(-?\d+\.?\d*)", 1) # Regex to capture integer or float
    .cast(pl.Float64)
    .alias("val_numeric")
)

expr_bp = (
    pl.col("event_full_name").str.contains("BLOOD PRESSURE")
)

ALGO_bp_cond = (
    pl.col("event_full_name").str.contains("BLOOD PRESSURE")&
    pl.col("MEAS_VALUE").is_not_null()
)

lf = lf.join(
        lf.filter(
            ALGO_bp_cond
        ).with_columns(
            pl.col("MEAS_VALUE").str.split("/").list.get(0).cast(pl.Float64).alias("sys_bp"),
            pl.col("MEAS_VALUE").str.split("/").list.get(1).cast(pl.Float64).alias("dia_bp")
        ).select("PAT_ENC_CSN_ID", "Event_DateTime", "sys_bp", "dia_bp"),
        on=['PAT_ENC_CSN_ID', "Event_DateTime"],
        how='left'
).with_columns(
    MAP=((pl.col("sys_bp")+(2.0*pl.col("dia_bp")))/3.0).cast(pl.Float64)
)

In [19]:
lf.filter(
    pl.any_horizontal(
        [expr_plat, expr_bilirubin, expr_creatin, expr_bp]
    )
).collect()['event_full_name'].value_counts(sort=True)

shape: (6, 2)
┌─────────────────────────────────┬────────┐
│ event_full_name                 ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u64    │
╞═════════════════════════════════╪════════╡
│ Flowsheet__BLOOD PRESSURE__Blo… ┆ 713804 │
│ Order Result - Lab__CREATININE… ┆ 80256  │
│ Order Result - Lab__PLATELETS_… ┆ 68705  │
│ Order Result - Lab__BILIRUBIN,… ┆ 33813  │
│ Order Result - Lab__PLT ESTIMA… ┆ 11252  │
│ Order Result - Lab__CREATININE… ┆ 294    │
└─────────────────────────────────┴────────┘

In [14]:
lf.filter(
    expr_plat | expr_bilirubin | expr_creatin | expr_bp
).collect()['event_full_name'].unique()

shape: (6,)
Series: 'event_full_name' [str]
[
	"Order Result - Lab__CREATININE…
	"Flowsheet__BLOOD PRESSURE__Blo…
	"Order Result - Lab__BILIRUBIN,…
	"Order Result - Lab__CREATININE…
	"Order Result - Lab__PLATELETS_…
	"Order Result - Lab__PLT ESTIMA…
]

In [11]:
# Platelet
expr_plat = (
    (pl.col('event_full_name').str.to_lowercase().str.contains("order result"))&
    (pl.col('event_full_name').str.to_lowercase().str.contains("platelet"))
)

expr_bilirubin = (
    (pl.col('event_full_name').str.to_lowercase().str.contains("order result"))&
    (pl.col('event_full_name').str.to_lowercase().str.contains("bili"))
)

expr_creatin = (
    (pl.col("event_full_name").str.to_lowercase().str.contains("creatin"))&
    (pl.col("event_full_name").str.to_lowercase().str.contains("order result"))
)

expr_bp = (
    pl.col("event_full_name").str.contains("BLOOD PRESSURE")
)

vasopressor_keywords = [
    "norepinephrine", "levophed", 
    "vasopressin", "vasostrict", 
    "phenylephrine", "neo-synephrine", 
    "dopamine", 
    "epinephrine", "adrenaline",  # <--- Added this (Critical for severe shock)
    "giapreza", "angiotensin"     # <--- Added this (Newer shock drug, rare but possible)
]

expr_vasopressors_final = (
    # 1. Match ANY of the drug names
    (pl.col("event_full_name").str.to_lowercase().str.contains_any(vasopressor_keywords)) &
    
    # 2. EXCLUDE "Push Doses" (Transient use)
    # This applies your specific Phenylephrine logic to ALL pressors just to be safe
    ~(pl.col("event_full_name").str.to_lowercase().str.contains("push dose")) &
    ~(pl.col("event_full_name").str.to_lowercase().str.contains("bolus")) &
    
    # 3. EXCLUDE Specific small vial sizes (implies push dose, based on your findings)
    ~(pl.col("event_full_name").str.to_lowercase().str.contains(r"\b10 mg\b")) & 
    ~(pl.col("event_full_name").str.to_lowercase().str.contains(r"\b1 mg\b")) &
    
    # 4. EXCLUDE Diagnosis/Audit text (Keep only Orders/Admin)
    ~(pl.col("event_full_name").str.to_lowercase().str.contains("__other"))
)

In [ ]:
lf_labs_scored = lf_labs.with_columns(
    pl.when(pl.col("event_full_name").str.to_lowercase().str.contains("platelet"))
      .then(
          pl.when(pl.col("val_numeric") < 20).then(4)
            .when(pl.col("val_numeric") < 50).then(3)
            .when(pl.col("val_numeric") < 100).then(2)
            .when(pl.col("val_numeric") < 150).then(1)
            .otherwise(0)
      )
      .when(pl.col("event_full_name").str.to_lowercase().str.contains("bilirubin"))
      .then(
          pl.when(pl.col("val_numeric") >= 12.0).then(4)
            .when(pl.col("val_numeric") >= 6.0).then(3)
            .when(pl.col("val_numeric") >= 2.0).then(2)
            .when(pl.col("val_numeric") >= 1.2).then(1)
            .otherwise(0)
      )
      .when(pl.col("event_full_name").str.to_lowercase().str.contains("creatinine"))
      .then(
          pl.when(pl.col("val_numeric") >= 5.0).then(4)
            .when(pl.col("val_numeric") >= 3.5).then(3)
            .when(pl.col("val_numeric") >= 2.0).then(2)
            .when(pl.col("val_numeric") >= 1.2).then(1)
            .otherwise(0)
      )
      .alias("SOFA_Points")
      .cast(pl.Int32)
)

In [ ]:
expr_plat = (
    (pl.col('event_full_name').str.to_lowercase().str.contains("order result"))&
    (pl.col('event_full_name').str.to_lowercase().str.contains("platelet"))
)